Player Info: Delivering player info
NexusForever/NexusForever pull request #125
Opened 2019-03-24 16:01 UTC by kirmmin

- Used by Mail & Contacts, and probably other features to update the client about Names, Class, Race, etc. for associated Character ID
- Also includes the `WriteStirngFixed` method for `GamePacketWriter`

TODO: Probably needs some optimisation, like caching player data and not needing to make a DB request each time.

2019-03-24 20:18 UTC, Rawaho requested changes

2019-03-24 20:18 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Handler/MiscHandler.cs
> +            Character character = CharacterDatabase.GetCharacterById(request.CharacterId);
This should be asynchronous and handled as an event, having a blocking query in a session is bad due to the fact that all sessions are updated sequentially.

2019-03-25 00:11 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Handler/MiscHandler.cs
> +            Character character = CharacterDatabase.GetCharacterById(request.CharacterId);
This should be resolved, now. Pretty simple change, too. I like the simplicity of this :)

2019-03-25 23:45 UTC, Rawaho approved these changes

2019-03-25 23:48 UTC, merged