Realm Broadcast feature
NexusForever/NexusForever pull request #132
Opened 2019-04-01 02:59 UTC by kirmmin

2019-04-02 11:03 UTC, Rawaho requested changes

2019-04-02 11:03 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerRealmBroadcast.cs
> +        public byte Tier { get; set; } // 0 = Notification Windows & Chat Message; 1 = Notification Message centre screen & Chat Message; 2 = Chat Message
Maybe make this an enum rather than commenting on the value meanings.

2019-04-02 11:03 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/BroadcastHandler.cs
> +            if (parameters.Length > 2)
Try and reduce code indenting with multiple returns.

2019-04-02 11:03 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/BroadcastHandler.cs
> +            : base(true, "broadcast", "broadcastTier(0/1/2) message - Broadcast message to the realm using the given broadcast tier.")
This could be false to allow sending from the console?

2019-04-02 11:03 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/BroadcastHandler.cs
> +                foreach(WorldSession session in allSessions)
You want a space here along with braces around the content in the foreach, you want braces since the entire code block is larger than 1 line.

2019-04-02 11:03 UTC, Rawaho commented on Source/NexusForever.Shared/Network/NetworkManager.cs
> +        public static IEnumerable<T> GetSessions(Func<T, bool> func = null)
This would be better as 2 functions, it will make it more explicit that no predicate returns all sessions.

2019-04-02 17:53 UTC, kirmmin commented
@Rawaho Updated following your review.

2019-04-03 07:23 UTC, Rawaho approved these changes

2019-04-03 07:23 UTC, merged