Basic implementation of chat
NexusForever/NexusForever pull request #16
Opened 2018-11-29 12:16 UTC by lucas-jones

Creating pull request for feedback / comments

2018-11-29 16:47 UTC, Rawaho requested changes
A good start, just a few minor issues that need looking at.

2018-11-29 16:47 UTC, Rawaho commented on Source/NexusForever.WorldServer/Database/Character/CharacterDatabase.cs
> +        public static Model.Item GetItemById(ulong Id)
You shouldn't need to hit the database to find an item, you can do a local query on the players inventory.

2018-11-29 16:47 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Social/SocialManager.cs
> +            ChatChannelHanlers.Add(ChatChannel.Emote, HandleLocalChat);
Would be much cleaner if these were registered with an attribute rather than manually doing so.

2018-11-29 16:47 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Social/SocialManager.cs
> +        public static Dictionary<ChatChannel, ChatChannelHandler> ChatChannelHanlers = new Dictionary<ChatChannel, ChatChannelHandler>();
This doesn't need to be public from what I can see.

2018-11-29 16:47 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Social/SocialManager.cs
> +        public static readonly float LocalChatDistace = 155;
This doesn't need to be public from what I can see.

2018-11-29 16:47 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Social/SocialManager.cs
> +                if (entity is Player player)
You want to do the filtering in the ISearchCheck, create a new one that checks for distance _and_ if the entity is a player.

2018-11-29 16:47 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientChat.cs
> +    public class ChatLink
Keep a single class to a single source file unless it's nested.

2018-11-29 16:47 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerChat.cs
> +    public class ServerLinkedItemId : IWritable
Keep a single class to a single source file unless it's nested.

2018-11-29 18:39 UTC, fabianPas commented
What about XML documentation?

2018-12-02 01:09 UTC, Rawaho requested changes

2018-12-02 01:09 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Social/SocialManager.cs
> +                if (entity is Player player)
See comment above for clarification.

2018-12-02 01:09 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Map/SearchCheckRangeExcludePlayer.cs
> +            return entity != this.entity && base.CheckEntity(entity);
This functions should also check if the entity is a player and filter them out if not.
Reason being is you only send the chat packet to players, it removes the need to do it in HandleLocalChat.

2018-12-02 01:09 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientChat.cs
> +
3 classes above need to be separate files, only a single class to a source file unless it's a nested class.

2018-12-02 01:09 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientChat.cs
> +                if(Type == ChatLinkType.ItemGuid)
This really should be done with reflection to delegate what object to create.
This is an optional change, I'll probably change it in the future if not done by you.

2018-12-02 01:09 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerChat.cs
> +    public class ServerLinkedItemId : IWritable
Still relevant.

2018-12-03 15:34 UTC, lucas-jones commented on Source/NexusForever.WorldServer/Game/Map/SearchCheckRangeExcludePlayer.cs
> +            return entity != this.entity && base.CheckEntity(entity);
Ah ops. I renamed the class to SearchCheckRangeExcludeGridEntity but forgot to rename the file name...

I'll change it back to player specfic

2018-12-04 07:48 UTC, Rawaho approved these changes

2018-12-04 07:49 UTC, merged