Feature: World Prop usage by entities
NexusForever/NexusForever pull request #169
Opened 2019-06-01 00:41 UTC by kirmmin

2019-06-06 00:07 UTC, Rawaho requested changes

2019-06-06 00:07 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/DoorCommandHandler.cs
> +            );
There is no need to do a grid search for nearby doors, using visible entities will be enough since there should never be a need to open doors that the player can't see.

2019-06-06 00:07 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/DoorCommandHandler.cs
> +            );
Same as above.

2019-06-06 00:07 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/DoorCommandHandler.cs
> +            }
This isn't really a valid comment any more since you should remove the grid search but create a new search check if the future that only selects door entities rather then doing it after the fact.

2019-06-06 00:07 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Door.cs
> +            if (openForAll)
This will cause a desync of information between clients and the server if `openForAll` is false.
You are changing the state but only sending the result to a single player, this single player will see the door open, any new players coming into range will see it open but any characters that were nearby but haven't moved will see it closed.

2019-06-06 00:07 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Door.cs
> +            if (openForAll)
Same as above but in reverse.

2019-06-07 13:41 UTC, kirmmin commented on Source/NexusForever.WorldServer/Command/Handler/DoorCommandHandler.cs
> +            }
I've created a new Search Check, and I've also added a `GetVisibleEntities<T>` method to return all visible entities of a type.

2019-07-21 01:56 UTC, merged