Feature: Stance/Innate set & save
NexusForever/NexusForever pull request #174
Opened 2019-06-04 15:06 UTC by kirmmin

Also resolves some endless loop spell casting on bad innate abilities

2019-06-05 23:54 UTC, Rawaho requested changes

2019-06-05 23:54 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientInnateChange.cs
> +    public class ClientInnateChange : ServerPlayerInnate
A client packet should never inherit a server packet and vice versa.

2019-06-05 23:54 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPlayerInnate.cs
> +        public void Read(GamePacketReader reader)
Relating to the comment above, unless a packet is bidirectional it shouldn't inherit both IReadable and IWritable.
If the packet is in fact bidirectional name it appropriately.

2019-06-05 23:54 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPlayerInnate.cs
> +            writer.Write(InnateIndex, 2u);
Why is the innate index 8 bits in one packet and 2 bits in another?
Are you sure they are the same value?

2019-06-06 01:44 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPlayerInnate.cs
> +        public void Read(GamePacketReader reader)
It's not; I'll make this a Shared model.

2019-06-06 01:44 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientInnateChange.cs
> +    public class ClientInnateChange : ServerPlayerInnate
Yep. Sorry boss.

2019-06-06 01:45 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPlayerInnate.cs
> +            writer.Write(InnateIndex, 2u);
I am positive :) I confirmed in my sniffs - I also thought it was odd, but then this might be one of the first packets they wrote and they never bothered updating it?

2019-06-06 01:47 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPlayerInnate.cs
> +            writer.Write(InnateIndex, 2u);
My concern is it might be similar to the ServerCombatReward situation where multiple types of values are packed into the same field.
Looking at sniffs alone might not reveal this, having a look at the code in the client that sends and receives these packets would give more insight into if this was the case or not.

2019-06-06 01:49 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPlayerInnate.cs
> +            writer.Write(InnateIndex, 2u);
Gotcha; To add, the only LUA events I had firing, when I received the packet was the Stance Update one.
But, I will confirm in the client code :)

2019-06-07 12:11 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPlayerInnate.cs
> +            writer.Write(InnateIndex, 2u);
Updated packet handler inheritance.

Additionally, dug into the packet being passed to and from the client. The server packet is only handled by the StanceChange LUA event, and the client packet doesn't seem to be used for anything else that I can see.

2019-07-01 02:10 UTC, kirmmin commented
Dug into the packet being passed to and from the client. The server packet only fires the `StanceChange` LUA event, and the client packet doesn't seem to be used for anything else that I can see.

2019-07-21 03:00 UTC, merged