Remodels and Decor Linking
NexusForever/NexusForever pull request #197
Opened 2019-08-15 07:17 UTC by MahqasMayhem

Allows the server to handle, store, and distribute information regarding Housing Remodels and Decor Linking. Also provides a better fix to the issue of decor offsets, though a another
solution may need to be found in the future.

2019-08-15 20:26 UTC, Rawaho requested changes
Overall a great PR, only a few minor issues and queries.

2019-08-15 20:26 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Housing/Residence.cs
> +                if ((entry.Flags & 0x180) == 0)
0x0180 is 2 flags, 0x0080 and 0x0100, I would say only one of these actually determines if it is music or not.

2019-08-15 20:26 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Map/ResidenceMap.cs
> +                }
A nitpick but I might save to have modifying the offset in a nested function rather than in multiple places.
I would say eventually we will need one anyway once we understand the offsets some more.

2019-08-15 20:26 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Map/ResidenceMap.cs
> +            }
As above.

2019-08-15 20:26 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerHousingProperties.cs
> +                writer.Write(Ground);
Since an additional value has been added here do the values below still match?

2019-08-16 00:54 UTC, MahqasMayhem commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerHousingProperties.cs
> +                writer.Write(Ground);
As best as I know the values below are still good. Nothing was actually added here, it was simply given a value to write in, and arranged so that the packet would be written correctly. Previously values were being written in no particular order and that was causing the client to misassign that data. i.e. sky data was being written in as grounds, etc.

2019-09-06 08:23 UTC, myyanf commented on Source/NexusForever.WorldServer/Game/Housing/Residence.cs
> +                if ((entry.Flags & 0x180) == 0)
Oddly, the Flags setting for music in the HousingWallpaperInfo entries is 0x180. Dumping flag values for entries 1-4000  from the list, I see that roughly the first 285 entries (minus a couple) exist, and that other than music with its 0x180 setting, nothing else appears to use either flag. Given this, technically either flag alone would work to determine if the entry is music,

2019-09-26 12:17 UTC, merged