Core/RealmList: Reload servers and handle offline
NexusForever/NexusForever pull request #219
Opened 2019-11-07 01:04 UTC by kirmmin

Refreshes servers from database if the server list is deemed dirty

Note: This was written so that Admins could add/remove extra realms from their Auth table without having to bump any existing World Servers.

2019-11-07 10:35 UTC, Rawaho commented
The problem with this implementation is the updating of the servers happens on the world thread, this will block updating the next session while long running take such as synchronous database calls and TCP connections happen.
You really want all of that to happen in another thread.

2019-11-07 13:36 UTC, kirmmin commented
Thanks @Rawaho. Been a while since I've done a database lookup during a thread so I had forgotten this needs to run asynchronously when making database calls. I'll update appropriately :)

2019-11-07 14:45 UTC, kirmmin commented
@Rawaho, I've updated the code following your review. I'm still not 100% sure how await/async works in C#-world, so a follow up review will really help <3

2019-11-08 13:23 UTC, Rawaho commented
GetResult synchronously waits for an asynchronous task to complete which defeats the point in this scenario.

For the database calls you don't need to wrap the entire thing in a task, EF already has asynchronous methods to get data from the database.
Converting to ImmutableList afterwards can be synchronous as it will be quick compared to the database call.

You are also still pinging the world server on the world thread, this means that while the world server is trying to establish the connection to the other world server the thread is "paused" and no session or world updates can occur.

My suggestion would be to have either a long running task or separate thread continuously updating the server status and when you try and connect it just checks the model which will have an up to date status.

2019-11-08 13:27 UTC, kirmmin commented
Okay! I was tempted to go that way, but not sure how you felt about running an Update method on Server Manager, so opted not to. Sounds like it would've been a better way to go though :)
I'll refactor again, and hopefully get it right this time ;)

Thanks a lot!

2019-11-08 19:37 UTC, kirmmin commented
@Rawaho, I hope this'll be the last review you need to do on this. I've moved it to an Update loop and made the Ping check Asynchronous (I think). Please confirm I'm going in the right direction, when you have time, of course.

2019-11-10 14:04 UTC, kirmmin commented
Update ServerManager to use its own thread as discussed on Discord. While playing with a verification method, I also updated the `ServerHello` packet structure to have more named parameters.

This isn't the final form of the online status check, but this should be a good first start (assuming no further changes). :)

2019-11-19 07:08 UTC, Rawaho requested changes

2019-11-19 07:08 UTC, Rawaho commented on Source/NexusForever.Shared/Game/ServerManager.cs
> +        private double checkTimer;
Could be replaced with UpdateTimer.

2019-11-19 07:08 UTC, Rawaho commented on Source/NexusForever.Shared/Game/ServerInfo.cs
> +                PingHost(Model.Host, Model.Port);
Asynchronous function isn't awaited, could lead to thread safety issues.

2019-11-19 07:08 UTC, Rawaho commented on Source/NexusForever.Shared/Game/ServerInfo.cs
> +                await client.ConnectAsync(hostIP, port).ContinueWith(task =>
This probably doesn't need to be asynchronous as it is handled in a separate thread.

2019-11-19 07:08 UTC, Rawaho commented on Source/NexusForever.Shared/Game/ServerInfo.cs
> +        private double pingTimer;
Could be replaced with UpdateTImer.

2019-11-19 07:08 UTC, Rawaho commented on Source/NexusForever.Shared/Game/ServerInfo.cs
> +                PingHost(Model.Host, Model.Port);
Asynchronous function isn't awaited, could lead to thread safety issues.

2019-11-19 07:18 UTC, Fabi commented on Source/NexusForever.Shared/Game/ServerInfo.cs
> +                PingHost(Model.Host, Model.Port);
Unlikely. async functions with no Task as return type are not supposed to be awaited but will just run and not block the current method. Should be fine

2019-11-19 18:06 UTC, kirmmin commented on Source/NexusForever.Shared/Game/ServerInfo.cs
> +                await client.ConnectAsync(hostIP, port).ContinueWith(task =>
I've updated everything except this. I decided to keep it asynchronous because it was cleaner code but also meant that we didn't need to wait for a connection to 1 server to end before moving on to check the next, we can check them all in parallel, or near enough.

2019-12-06 10:18 UTC, merged