Core/Entities: Basic info commands
NexusForever/NexusForever pull request #256
Opened 2020-03-31 03:05 UTC by kirmmin

Added WorldSocketId in preparation for use in Plugs, Plug entities, and Decor entities

2020-04-04 23:07 UTC, Rawaho requested changes

2020-04-04 23:07 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/EntityCommandHandler.cs
> +            string text = "=============================\n";
Might be more efficient to use a StringBuilder as I would assume this might expand in the future.

2020-04-04 23:07 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/EntityCommandHandler.cs
> +            text += $"{GetCreatureName(targetEntity, context.Language)} | UnitId: {targetEntity.Guid}\n";
Same as above.

2020-04-04 23:07 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/WorldEntity.cs
> +        public EntityModel Model { get; private set; }
What's the reason for storing the model on the entity?

2020-04-04 23:07 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/WorldEntity.cs
> +        public ushort WorldSocketId { get; private set; }
Always 0?
Isn't set from the model from what I can see.

2020-04-04 23:17 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/WorldEntity.cs
> +        public EntityModel Model { get; private set; }
Specifically for the DB ID. I figured it would be useful when "world building" later, to be able to see what the DB ID was that you needed to adjust.

2020-04-04 23:17 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/WorldEntity.cs
> +        public EntityModel Model { get; private set; }
In hindsight, maybe I can just store DB ID for the Entity, because not much else will be necessary.

2020-04-04 23:17 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/WorldEntity.cs
> +        public ushort WorldSocketId { get; private set; }
Yeah, this is my mistake. Well spotted. I'll update this in the constructor.

2020-04-05 01:56 UTC, kirmmin commented
Ready for re-review.

2020-04-05 12:58 UTC, SilentCLD requested changes
Overall looks good to me, just a couple of things i noticed

2020-04-05 13:00 UTC, SilentCLD commented on Source/NexusForever.WorldServer/Command/Handler/EntityCommandHandler.cs
> +//using NexusForever.WorldServer.Game.Map.Search;
Should be removed if not used

2020-04-05 13:00 UTC, SilentCLD commented on Source/NexusForever.WorldServer/Command/Handler/EntityCommandHandler.cs
> +            }
These ifs can be merged with an OR ( || ) to avoid duplication of the error message

2020-04-05 13:00 UTC, SilentCLD commented on Source/NexusForever.WorldServer/Command/Handler/EntityCommandHandler.cs
> +            }
Unnecessary braces

2020-04-08 09:49 UTC, Rawaho approved these changes

2020-04-08 09:49 UTC, merged