Inventory/Crafting: Supply Satchel support
NexusForever/NexusForever pull request #259
Opened 2020-04-04 04:31 UTC by kirmmin

This PR enables the ability to use the Supply Satchel for item storage. You can move items between the Inventory and the Supply Satchel. There is no consumption of items in the Supply Satchel through Crafting at this time.

2020-04-04 23:23 UTC, Rawaho requested changes

2020-04-04 23:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/SupplySatchelManager.cs
> +            string text = "";
Seems like debug logging that can be removed?

2020-04-04 23:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/SupplySatchelManager.cs
> +                throw new ArgumentNullException("entry");
ArgumentNullException refers to a parameter in the function.
You would use it like ArgumentNullException(nameof(parameterName))
In this case it's the invalid exception type to be used here

2020-04-04 23:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/SupplySatchelManager.cs
> +                throw new ArgumentNullException("entry");
As above.

2020-04-04 23:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/SupplySatchelManager.cs
> +                throw new ArgumentOutOfRangeException("amount");
ArgumentOutOfRangeException(nameof(amount))

2020-04-04 23:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/SupplySatchelManager.cs
> +                throw new ArgumentNullException("entry");
As above.

2020-04-04 23:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/TradeskillMaterial.cs
> +            if (saveMask != TradeskillMaterialSaveMask.None)
Try and reduce indentation.

2020-04-04 23:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Handler/ItemHandler.cs
> +        public static void HandleClient012A(WorldSession session, ClientItemMoveToSupplySatchel moveToSupplySatchel)
Rename the handlers to the packet names.

2020-04-04 23:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Handler/ItemHandler.cs
> +        public static void HandleClient0184(WorldSession session, ClientItemMoveFromSupplySatchel request)
Rename the handlers to the packet names.

2020-04-05 02:22 UTC, kirmmin commented
Ready for re-review. Thanks for the pointers.

2020-04-08 09:51 UTC, Rawaho approved these changes

2020-04-08 09:54 UTC, merged