Implementation of Residence Flags settings.
NexusForever/NexusForever pull request #263
Opened 2020-04-12 14:48 UTC by myyanf

Implements the flags for hiding ground clutter and neighbor skyplots.

2020-04-13 01:28 UTC, Rawaho requested changes
Looks good, just a small query about the packet structure.

2020-04-13 01:28 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientHousingFlagsUpdate.cs
> +            Flags = reader.ReadEnum<ResidenceFlags>(3u);
Where do the 3 bits come from?
Having a look at the packet writer in the client just shows the player identity and a uint32

2020-04-14 06:22 UTC, myyanf commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientHousingFlagsUpdate.cs
> +            Flags = reader.ReadEnum<ResidenceFlags>(3u);
So I can't say I have a good answer for where they come from as I'm just structuring this off of packet data and a guess, and not off of anything more useful. However, if I change this to just read the identity and read Flags with reader.ReadEnum<ResidenceFlags>(32u), I get the following message from the server (develop branch with only this PR added in):
[WARN][Session] Failed to read entire contents of packet ClientHousingFlagsUpdate
So I had assumed the three extra bits were the flag, and the uint32 was something else unknown at this time.
I'll be more than happy to switch this around so that the flags enum is read as 32bit, but unless I'm missing something obvious (and I well might be), I'd still need to read in the 3 bits to avoid the warning message. Any pointers on how to proceed would be appreciated.
Thanks much for your help and feedback.

2020-04-14 13:40 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientHousingFlagsUpdate.cs
> +            Flags = reader.ReadEnum<ResidenceFlags>(3u);
@myyanf: https://gist.github.com/kirmmin/2eab3aeb4b98420cca5effe812677ca7 - This is the full packet handler from the client. I haven't dug into which value is which, but this should help you check.

2020-04-16 09:40 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientHousingFlagsUpdate.cs
> +            Flags = reader.ReadEnum<ResidenceFlags>(3u);
I'm guessing the values are harvest and garden split related.
This packet is sent from SetNeighborHarvestSplit and SetNeighborGardenSplit as well.

2020-04-16 11:10 UTC, merged