Entity/RewardProperties: Account Tier based Reward Properties. Retail-like.
NexusForever/NexusForever pull request #277
Opened 2020-04-28 00:51 UTC by kirmmin

This provides the necessary functionality to send unlocks to the client based on their Account Tier. The Account Tier itself is unimportant for the purpose of this feature. My goal was to make sure that we were sending things like Guild/Circle functionality, Bag Slots, Bank Slots, Auction and Commodity Counts appropriately. The Game Tables have this data available in it, so I am using them to generate the necessary properties.
In addition, the EntitlementManager can now be used to update the Client immediately. When I "purchase" a Costume slot, it is immediately reflected in my Character Pane without relog/zone. 

This was necessary work to get Store Purchasing working. This PR, #272, #273, and #275, are all necessary for Store Purchases to work. Outside of the added functionality, with the Store Purchasing, the majority of "Account features" should be complete.

2020-04-28 01:08 UTC, Rawaho requested changes

2020-04-28 01:08 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/RewardProperty.cs
> +        public ServerRewardPropertySet.RewardProperty BuildNetworkModel()
Use IBuildable

2020-04-28 01:08 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Static/AccountTier.cs
> +﻿using System;
Remove unneeded includes

2020-04-28 01:08 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Static/PremiumSystem.cs
> +﻿using System;
Remove unneeded includes

2020-04-28 01:08 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerAccountTier.cs
> +using System.Collections.Generic;
Remove unneeded includes

2020-04-28 01:08 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +        public Dictionary<(RewardPropertyType, uint), RewardProperty> Rewards { get; } = new Dictionary<(RewardPropertyType, uint), RewardProperty>();
Should really move this and any methods related to it to a manager, this could be a new one or the existing entitlement manager since they seem related.

2020-04-28 01:08 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +        private void CalculateRewardProperties()
See above

2020-04-28 01:08 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/AssetManager.cs
> +            foreach (var rewardPropTier in rewardProps)
Could clean this nested foreach with maybe SelectMany?

2020-04-28 01:08 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/AssetManager.cs
> +            var rewardProps = GameTableManager.Instance.RewardPropertyPremiumModifier.Entries.Where(i => (PremiumSystem)i.PremiumSystemEnum == PremiumSystem.Hybrid).GroupBy(i => i.Tier);
With long nested LINQ statements try and have each new call on a new line.
```
GameTableManager.Instance.RewardPropertyPremiumModifier.Entries
	.Where(i => (PremiumSystem)i.PremiumSystemEnum == PremiumSystem.Hybrid)
	.GroupBy(i => i.Tier);
```

2020-04-28 01:08 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/AssetManager.cs
> +            rewardPropertiesByTier = entries.ToImmutableDictionary(e => e.Key, e=> e.Value.ToImmutableList());
I believe you want ToImmutable rather than ToImmutableDictionary for entries?

2020-04-28 01:08 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/EntitlementManager.cs
> +                if (!session.Player.Rewards.TryGetValue(((RewardPropertyType)rewardPropertyEntry.RewardPropertyId, rewardPropertyEntry.RewardPropertyData), out RewardProperty rewardProperty))
Try and reduce direct public access to a collection like this, encapsulate with methods.

2020-04-28 01:25 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/AssetManager.cs
> +            rewardPropertiesByTier = entries.ToImmutableDictionary(e => e.Key, e=> e.Value.ToImmutableList());
For this, I did it the same way as the one above because I wanted to build an `ImmutableDictionary` and create an `ImmutableList` at the same time. I can see if `ToImmutable` allows the same overload, though.

2020-04-28 01:29 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/AssetManager.cs
> +            rewardPropertiesByTier = entries.ToImmutableDictionary(e => e.Key, e=> e.Value.ToImmutableList());
It doesn't. I can refacotr, but it will be more lines of code and  could be more confusing. It might make sense to leave it as it is to keep it as clean as possible?

2020-04-28 02:01 UTC, kirmmin commented
Refactored following the Review. I moved the methods to the `EntitlementManager` per your suggestion and made sure I encapsulated with methods. Not sure why I didn't do it prior to submitting the PR other than just overlooked it. I left one of the conversations outstanding because I didn't want to resolve until you've answered.

2020-11-19 11:37 UTC, Rawaho approved these changes

2020-11-19 11:38 UTC, merged