Entity/Movemment: Fix Rotation on spline
NexusForever/NexusForever pull request #316
Opened 2020-10-02 01:09 UTC by kirmmin

2020-10-02 06:12 UTC, Rawaho requested changes
My suggestion to handling this would be tracking the angle to the next spline point in both directions, this can be calculated when the spline is created (in fact the code is already there for it)
This would also actually allow for proper handling with keys rather than default which retail didn't do

2020-10-02 06:12 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Movement/MovementManager.cs
> +            return command?.UnitId > 0 ? command?.UnitId : null;
Is there a need to check for 0 here since you are using nullable?

2020-10-02 06:12 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Movement/MovementManager.cs
> +                Blend = true
What does blend actually do at the client?

2020-10-02 06:12 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Movement/MovementManager.cs
> +            commands.Remove(EntityCommand.SetRotationDefaults);
You are adding SetRotationDefaultsCommand above but removing it here, does this serve any purpose?

2020-10-02 06:12 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Movement/MovementManager.cs
> +                Position = new Position(splinePath.GetPreviousPosition().GetRotationTo(position))
This is suppose to be the current facing direction? Seems like a very round about way of doing it

2020-10-02 06:12 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Movement/MovementManager.cs
> +            }, !(owner is Player));
What is the reason for this?

2020-10-02 06:12 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/WorldEntity.cs
> +            }
Not sure if we actually want setting the rotation to trigger the movement manager.
For example before a teleport, the rotation is set, this would trigger an entity command.

2020-10-02 06:23 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Movement/MovementManager.cs
> +                Blend = true
It makes the entity face the direction it's walking in. My packet logs showed this when entities were in combat, or walking random directions - I didn't have the keys stuff happening.

2020-10-02 06:24 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Movement/MovementManager.cs
> +                Position = new Position(splinePath.GetPreviousPosition().GetRotationTo(position))
Correct. What would be your suggestion?

2020-10-02 06:27 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Movement/MovementManager.cs
> +            commands.Remove(EntityCommand.SetRotationDefaults);
Nope. This was me testing, and it's not necessary to remove on here.

2020-10-02 06:29 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Movement/MovementManager.cs
> +            }, !(owner is Player));
This is so we set the command for the Player but do not emit it. This only matters for the EntityCreate packet when another Player runs into range. See #315

2024-04-06 15:13 UTC, Rawaho commented
Resolved in 68d03abac5d86a496cb14a30faedc4ddec2c39cc

2024-04-06 15:13 UTC, closed without merging