[WIP] Add vendor and basic currency support
NexusForever/NexusForever pull request #33
Opened 2018-12-01 04:10 UTC by Matt-Hurd

Should've made more commits than this, ugh.

Implemented:
* Add in-memory implementation of currencies
* Basic Vendor buy/sell, manipulating items and currencies

Unimplemented:
* Most items don't have explicit values set and are instead calculated based on quality, item type, etc. This equation will need to be figured out.
* Buyback from vendors isn't set
* Reason for add/delete from inventory is not being set to the proper value

2018-12-01 04:43 UTC, Rawaho requested changes
An awesome start, just a few issues that need correcting.
I have enjoyed watching you stream this, the offer still stands from Discord :)

2018-12-01 04:43 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Handler/VendorHandler.cs
> +            }
Would be better if this was encapsulated into say VendorInfo

2018-12-01 04:43 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +        public ulong[] Currencies { get;  }
Would be better if this was encapsulated having a bunch of functions that can modify currencies along with checking for valid currencies, amounts, overflows, ect...

2018-12-01 04:43 UTC, Rawaho commented on Source/NexusForever.Shared/Network/Message/GameMessageOpcode.cs
> +        ServerCurrencyGainText          = 0x00DD,
Server packet names should based off any LUA events the handler in the client may call while processing.
In the case of 0x00DD it happens to call ChannelUpdate_Loot, maybe something like ServerChannelUpdateLoot would be better.

2018-12-01 04:43 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Handler/VendorHandler.cs
> +            if (session.Player.Currencies[itemEntry.CurrencyTypeId0] < (itemEntry.CurrencyAmount0 * costMultiplier))
Adding to the comment from before, it would be better if this was encapsulated with something like GetCurrency(123).

2018-12-01 04:43 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Handler/VendorHandler.cs
> +                    CurrencyId = (byte)((itemEntry.CurrencyTypeId0 & 0xFF) - 1),
You sure of ((itemEntry.CurrencyTypeId0 & 0xFF) - 1)?

2018-12-01 04:43 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCurrencyGainText.cs
> +            writer.Write((CurrencyId & 0b0001) != 0);
This can be writer.Write(CurrencyId , 4);
The only issues I have though is another packet writes currency as 5 bits and this one 4, you sure this is actually the same type?

2018-12-01 04:57 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCurrencyGainText.cs
> +            writer.Write((CurrencyId & 0b0001) != 0);
Nope! The ordering of the currencies is even different than it is in the DB.

2018-12-01 08:46 UTC, Matt-Hurd commented on Source/NexusForever.Shared/Network/Message/GameMessageOpcode.cs
> +        ServerCurrencyGainText          = 0x00DD,
Resolved for this opcode, will get names for other opcodes soon.

2018-12-01 08:46 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCurrencySet.cs
> +            writer.Write(CurrencyId - 1, 5);
Still not sure about this...

2018-12-01 08:46 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCurrencySet.cs
> +            writer.Write(CurrencyId - 1, 5);
But it works ¯\_(ツ)_/¯

2018-12-01 08:47 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Network/Message/Handler/VendorHandler.cs
> +                session.Player.CurrencyManager.CurrencyAddCount((byte)itemEntry.CurrencyTypeId0, (uint)(itemEntry.CurrencyAmount0SellToVendor * sellMultiplier));
Going to get these to ~100 characters long

2018-12-01 08:47 UTC, Matt-Hurd commented
This PR requires the GameTable fix, not included because it's out of scope.

2018-12-03 07:15 UTC, Matt-Hurd commented
Splitting into multiple PRs for easier maintainability

2018-12-03 07:15 UTC, closed without merging