Rapid transport cost + cooldown
NexusForever/NexusForever pull request #331
Opened 2020-10-23 16:24 UTC by mifrgr

Handles Payment and and look for cooldown. Thanks to Kirmmin for his help!

2020-10-23 16:38 UTC, MaxtorCoder requested changes
Too many magic numbers, also separate branch would be neato

2020-10-23 16:38 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Game/Spell/SpellEffectHandler.cs
> +             if (info.Entry.SpellId == 82922)
Magic number MonkaW

2020-10-23 16:38 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Game/Spell/SpellEffectHandler.cs
> +            else if (info.Entry.SpellId == 82956)
Another magic number MonkaW

2020-10-23 16:38 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            TaxiRouteEntry taxiRoute = GameTableManager.Instance.TaxiRoute.GetEntry(7);
Magic

2020-10-23 16:38 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            GameFormulaEntry spellEntry = GameTableManager.Instance.GameFormula.GetEntry(1307);
Magic

2020-10-23 16:38 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            GameFormulaEntry costEntry = GameTableManager.Instance.GameFormula.GetEntry(1310);
Magic

2020-10-23 18:27 UTC, kirmmin requested changes

2020-10-23 18:27 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            if (Shared.MathsExtensions.GetDistance3D(session.Player.Position, destinationPostion) < 200)
To keep this consistent with other places in the code, you should probably do:
```
if (session.Player.Position.GetDistance3D(destinationPosition) < 200f)
```

2020-10-23 18:27 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            else if (cooldown > 0 && session.AccountCurrencyManager.CanAfford(AccountCurrencyType.ServiceToken, serviceTokenPrice))
The `else if` is redundant here. The return statements in each of these if statements won't ever fire and is inconsistent with the rest of the code base. I would change all of these `else if` statements to `if`.

2020-10-23 18:27 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
>              {
Again, to keep this consistent with the rest of the codebase, I would remove the braces `{` when you're only executing one line below:

```
if (session.Player.Map.Entry.Id == worldLocation.WorldId) 
   creditPrice = (ulong)(creditBasePrice * costEntry.Dataint01 * taxiNode.ContentTier + Shared.MathsExtensions.GetDistance3D(session.Player.Position, destinationPostion));
else
   creditPrice = (ulong)(costEntry.Datafloat01 * taxiNode.ContentTier + creditBasePrice * costEntry.Dataint01 * taxiNode.ContentTier);
```

2020-10-23 19:59 UTC, mifrgr commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            GameFormulaEntry spellEntry = GameTableManager.Instance.GameFormula.GetEntry(1307);
Added const

2020-10-23 19:59 UTC, mifrgr commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            TaxiRouteEntry taxiRoute = GameTableManager.Instance.TaxiRoute.GetEntry(7);
Added const

2020-10-23 19:59 UTC, mifrgr commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            GameFormulaEntry costEntry = GameTableManager.Instance.GameFormula.GetEntry(1310);
Added const

2020-10-23 20:00 UTC, mifrgr commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            if (Shared.MathsExtensions.GetDistance3D(session.Player.Position, destinationPostion) < 200)
Done

2020-10-23 20:00 UTC, mifrgr commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            else if (cooldown > 0 && session.AccountCurrencyManager.CanAfford(AccountCurrencyType.ServiceToken, serviceTokenPrice))
Done

2020-10-23 20:00 UTC, mifrgr commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
>              {
Done

2020-10-27 13:45 UTC, alex-anderson156 commented
@mifrgr Did you forget to add [GameData] to the TaxiRoute table in the GameTableManager? without adding that i cannot get this to work.

2020-10-27 15:03 UTC, mifrgr commented
> @mifrgr Did you forget to add [GameData] to the TaxiRoute table in the GameTableManager? without adding that i cannot get this to work.

Yeah, I did, thanks, I will edit this when I'm at home

2020-10-27 17:26 UTC, mifrgr reviewed
All requested changes should be done now

2020-11-15 19:17 UTC, alex-anderson156 approved these changes

2020-11-17 14:57 UTC, xNxExOx requested changes
Validate before actions, not after them.

2020-11-17 14:57 UTC, xNxExOx commented on Source/NexusForever.WorldServer/Game/Spell/SpellEffectHandler.cs
> +             if (info.Entry.SpellId == spellIdRapidTransportCredits)
substracting currency should happen before actual teleportation, because if player does not have enough to teleport it will throw, but this way he/she would already be teleported for free.

2020-11-17 14:57 UTC, xNxExOx commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +
remove empty lines between `if` and `else`

2020-11-17 14:57 UTC, xNxExOx commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +                return;
validations should be before actually "casting" the spell

2020-11-17 14:57 UTC, xNxExOx commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            if (cooldown > 0 && session.AccountCurrencyManager.CanAfford(AccountCurrencyType.ServiceToken, serviceTokenPrice))
`cooldown` does not provide error message, is it intentional, because client should not be able to use it at when on cooldown, and informing "cheater" is not important? I think it is at least worth a comment.

2020-11-17 14:58 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Game/Spell/SpellEffectHandler.cs
> +             if (info.Entry.SpellId == spellIdRapidTransportCredits)
There's also an additional space at the `if` and extra line

2020-11-17 17:25 UTC, mifrgr commented on Source/NexusForever.WorldServer/Game/Spell/SpellEffectHandler.cs
> +             if (info.Entry.SpellId == spellIdRapidTransportCredits)
This is the effect handler. It'll only fire when the spell has been completely cast. The requirements has already been checked at this point, and if the player couldn't afford it, the spell wont be cast.

2020-11-17 17:26 UTC, mifrgr commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +
Done

2020-11-17 17:26 UTC, mifrgr commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +                return;
Done

2020-11-17 17:26 UTC, mifrgr commented on Source/NexusForever.WorldServer/Network/Message/Handler/CharacterHandler.cs
> +            if (cooldown > 0 && session.AccountCurrencyManager.CanAfford(AccountCurrencyType.ServiceToken, serviceTokenPrice))
The opcode that the client sends is the same regardless of whether the spell is on cooldown or not. So even if a cheater tried to get the RT for money, the server would still deduct the service tokens because it checks whether the spell is on cooldown. Cheating would be completely pointless in this case.

2020-11-17 17:56 UTC, xNxExOx requested changes
validations should be before performing the action

2020-11-17 17:56 UTC, xNxExOx commented on Source/NexusForever.WorldServer/Game/Spell/SpellEffectHandler.cs
> +
even thou it might have been checked it does not mean player could not have spend the currency elsewhere in the meantime and in that case player would get teleported for free.

2020-11-17 18:25 UTC, mifrgr commented on Source/NexusForever.WorldServer/Game/Spell/SpellEffectHandler.cs
> +
You're right, thanks, done.

2020-11-17 19:03 UTC, xNxExOx approved these changes

2021-02-05 19:38 UTC, MaxtorCoder approved these changes

2021-02-08 03:14 UTC, Rawaho commented
From what I can see these checks should be handled in a prerequisite handler, id 269 is only used by spells 82922 and 82956.
Handling the checks in the spell effect has the problem that the spell has already cast by that point, we can't send the correct cast result when it fails due to lack of currency or invalid rapid transport node.
I'm going to extend the prerequisite manager to handle this correctly and do a bit of a rework.

2021-03-22 21:06 UTC, kirmmin approved these changes

2024-12-08 06:04 UTC, merged