Currency implementation
NexusForever/NexusForever pull request #38
Opened 2018-12-03 07:21 UTC by Matt-Hurd

Follow-up PR: https://github.com/Matt-Hurd/NexusForever/pull/1

~Requires #39~

2018-12-04 00:29 UTC, Matt-Hurd commented
Commits got fucky on merge, should've rebased instead :(

2018-12-04 01:33 UTC, Rawaho requested changes

2018-12-04 01:33 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +            }
Wouldn't it be better to send this in a single packet ServerPlayerCreate?

2018-12-04 01:33 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCurrencyChanged.cs
> +            writer.Write(CurrencyId - 1, 5);
I'm still not certain on this, it just doesn't look right.
If it works for the time being I see no reason to stop the PR because of it but it's something I will look into at some point.

2018-12-04 03:59 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +            }
Oh, I forgot that was in there. Yep.

2018-12-04 07:51 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +            }
It seems like sending it in ServerPlayerCreate doesn't update the client. Is it possible that ServerPlayerCreate is incorrect?

2018-12-05 02:03 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCurrencyChanged.cs
> +            writer.Write(CurrencyId - 1, 5);
Left a comment about it, I really can't figure out why this is.

2018-12-06 14:36 UTC, Rawaho approved these changes

2018-12-06 14:42 UTC, merged