[Entitlement/Core] Support Entitlement Flags
NexusForever/NexusForever pull request #396
Opened 2021-12-04 01:40 UTC by kirmmin

2021-12-04 01:58 UTC, Fabi commented on Source/NexusForever.WorldServer/Game/Entity/Static/EntitlementFlag.cs
> +    public enum EntitlementFlag
Please define absolute values here for each flags. You do not want a normal enumeration here. C# does not  automatically do a 0, 1, 2, 4, 8, ...
You also might want to name it Entitlements or EntitlementFlags. Do not singular name flags.

2021-12-05 06:28 UTC, Rawaho requested changes

2021-12-05 06:28 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/EntitlementCommandCategory.cs
> +            if (targetPlayer != context.Invoker && !(context.Invoker as Player).Session.AccountRbacManager.HasPermission(Permission.GMFlag))
My suggestion would be to not reuse RBAC permissions.
The GMFlag permission should really be used only to display the GM flag in chat, not general GM permissions.

2021-12-05 06:28 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Entitlement.cs
> +                if (value > Entry.MaxCount)
Would it be better to have an exception here rather than swallowing?

2021-12-05 06:28 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Static/EntitlementFlags.cs
> +using System.Threading.Tasks;
Unused includes should be removed.

2021-12-05 06:28 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/EntitlementCommandCategory.cs
> +        public void HandleEntitlementCommandAccountAdd(ICommandContext context,
Might want to update to description and function name since this now does both character and account entitlements.

2021-12-05 06:28 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/EntitlementManager.cs
> +        /// <exception cref="ArgumentException"></exception>
Update comment.

2021-12-05 08:09 UTC, Fabi commented on Source/NexusForever.WorldServer/Game/Entity/Entitlement.cs
> +                if (value > Entry.MaxCount)
dis is not swallowing

2021-12-05 08:15 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Entitlement.cs
> +                if (value > Entry.MaxCount)
It's taking a value that should be considered an exception and setting it back within a acceptable range.
It's hiding a potential problem, it should really throw an exception to fail early.

2021-12-13 07:06 UTC, Rawaho commented on Source/NexusForever.WorldServer/Command/Handler/EntitlementCommandCategory.cs
> +            if (targetPlayer != context.Invoker && !(context.Invoker as Player).Session.AccountRbacManager.HasPermission(Permission.GMFlag))
@kirmmin going to tag you since you missed the comments on the other PR as well LOL

2022-01-01 06:27 UTC, steventmayer commented on Source/NexusForever.WorldServer/Game/Entity/EntitlementManager.cs
> +            GenericError CheckEntitlement(EntitlementEntry entry)
Do you feel the embedded function is more readable than a private function on this class? The CheckEntitlement seems to be a useful function that could be shared.

2022-02-14 07:31 UTC, merged