[Guilds/Core] Allow guilds with different GuildTypes to have the same name
NexusForever/NexusForever pull request #398
Opened 2021-12-08 04:22 UTC by brannon-penrod

You should now be able to create a Guild, Circle and Community with the same name.

2021-12-10 05:55 UTC, Rawaho requested changes
Just a few code style changes but functionally looks good.

2021-12-10 05:55 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Guild/GlobalGuildManager.cs
> +                    if (ReferenceEquals(x.Item2, y.Item2)) return true;
To follow code style in the rest of the project return should be on a separate line.

2021-12-10 05:55 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Guild/GlobalGuildManager.cs
> +        private class GuildNameEqualityComparer : IEqualityComparer<(GuildType, string)>
Might be better to move the comparer to a separate file to reduce clutter in a already large class.

2021-12-10 05:55 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Guild/GlobalGuildManager.cs
> +            public bool Equals((GuildType, string) x, (GuildType, string) y)
To follow code style of the rest of the project, tuple members should be named or deconstructed.

2021-12-10 06:23 UTC, brannon-penrod commented on Source/NexusForever.WorldServer/Game/Guild/GlobalGuildManager.cs
> +            public bool Equals((GuildType, string) x, (GuildType, string) y)
When I try to name the tuple members, I get an error stating that the tuple names need to be the same as those in the Interface method, which I don't think I can change.

2021-12-10 07:08 UTC, MaxtorCoder requested changes

2021-12-10 07:08 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Game/Guild/GuildNameEqualityComparer.cs
> +using System.Threading.Tasks;
Remove any unused directives here

2021-12-10 07:08 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Game/Guild/GuildNameEqualityComparer.cs
> +    internal class GuildNameEqualityComparer : IEqualityComparer<(GuildType, string)>
```suggestion
    internal class GuildNameEqualityComparer : IEqualityComparer<(GuildType Type, string Name)>
```

2021-12-10 07:08 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Game/Guild/GuildNameEqualityComparer.cs
> +            }
```suggestion
        public bool Equals((GuildType Type, string Name) x, (GuildType Type, string Name) y)
        {
            if (x.Type == y.Type)
            {
                if (ReferenceEquals(x.Name, y.Name))
                    return true;

                if (x.Name is null)
                    return false;

                if (y.Name is null)
                    return false;

                if (x.Name.GetType() != y.Name.GetType())
                    return false;

                return string.Equals(x.Name, y.Name, StringComparison.InvariantCultureIgnoreCase);
            }
```
 This should work with naming tuple members

2021-12-10 07:08 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Game/Guild/GlobalGuildManager.cs
> +        private readonly Dictionary<(GuildType, string), ulong> guildNameCache = new(new GuildNameEqualityComparer());
I guess name the tuple members here as well?

2021-12-10 07:43 UTC, brannon-penrod commented on Source/NexusForever.WorldServer/Game/Guild/GuildNameEqualityComparer.cs
> +            }
Thanks. Brainfart.

2021-12-11 11:49 UTC, Rawaho approved these changes

2021-12-11 11:50 UTC, merged