Fixed crashes when parameters are omitted.
NexusForever/NexusForever pull request #40
Opened 2018-12-03 22:00 UTC by IceReaper

When creating an account, with too less parameters, the world server should not crash.

2018-12-09 07:09 UTC, Rawaho commented
Might be better to have some global solution for this, maybe in the attribute have expected parameter amount which is checked before invoke?

2018-12-10 14:57 UTC, jasoncouture requested changes

2018-12-10 14:57 UTC, jasoncouture commented on Source/NexusForever.WorldServer/Command/Handler/AccountCommandHandler.cs
> +                return;
Instead of just returning, you should call await SendHelpAsync(context) first, to show the help text to the user.

2018-12-10 14:57 UTC, jasoncouture commented on Source/NexusForever.WorldServer/Command/Handler/AccountCommandHandler.cs
> +                return;
See previous comment about await SendHelpAsync(context);

2018-12-11 01:09 UTC, jasoncouture approved these changes
Looks good.

2018-12-12 15:56 UTC, merged