Option to generate map and table files on WorldServer build
NexusForever/NexusForever pull request #400
Opened 2021-12-11 18:03 UTC by mgasparel

This adds msbuild parameters to the WorldServer project which allow a user to extract game table files, as well as generate base map files.

Example command which generates both the /tbl and /map folders, populated in the WorldServer's build output directory:
`dotnet build /p:"WsInstallDir=H:\Wildstar\;ExtractGameTables=true;GenerateMapFiles=true"`

I ended up adding an option to the MapGenerator to allow us to specify the output directory. I could have created then moved the files, but an output directory seemed like a reasonable addition.

I noticed that the server installation guide is on @Rawaho fork, so I didn't update the docs in this PR.

This is just a qol update to help simplify first-time setup for local development.

2021-12-13 07:04 UTC, Rawaho requested changes
Overall good PR, only a very minor change and suggestion (not required!).
I personally have never really played around with target files but I do like the idea.

2021-12-13 07:04 UTC, Rawaho commented on Source/NexusForever.MapGenerator/ExtractionManager.cs
> +        string outputDir;
To follow code style access modifier required.

2021-12-13 07:04 UTC, Rawaho commented on Source/NexusForever.MapGenerator/MapGenerator.cs
> +            if ((parameters.Extract || parameters.Generate) && !string.IsNullOrEmpty(parameters.OutputDir))
Potentially default to original local directory if no explicit output directory is supplied?

2021-12-15 03:30 UTC, mgasparel commented on Source/NexusForever.MapGenerator/MapGenerator.cs
> +            if ((parameters.Extract || parameters.Generate) && !string.IsNullOrEmpty(parameters.OutputDir))
It's not super intuitive, but this does actually fall back to the old behaviour if no path is specified. 

When `Path.Combine(outputDir, "tbl");` is run and `outputDir` is an empty string, it doesn't throw and you end up with a relative path like we did before this change. Tested the behavior on Windows and Linux.

2021-12-15 03:31 UTC, mgasparel commented on Source/NexusForever.MapGenerator/ExtractionManager.cs
> +        string outputDir;
Fixed. Thoughts on generating an .editorconfig?

2021-12-18 01:50 UTC, merged