Added customer survey
NexusForever/NexusForever pull request #409
Opened 2022-04-26 21:01 UTC by ChargeIn

Added customer survery handling.

2022-04-27 07:53 UTC, MaxtorCoder commented
Please follow proper C# and NF code styles, there are many examples 🙏🏼

2022-04-27 19:36 UTC, ChargeIn commented
> Please follow proper C# and NF code styles, there are many examples 🙏🏼

Sorry my bad, I adjusted the style according to the wiki.

2022-05-07 04:32 UTC, Matt-Hurd commented on Source/NexusForever.Shared/Network/Message/GameMessageOpcode.cs
> +        ClientCustomerSurveyResponse   = 0x033F,
Misaligned

2022-05-07 04:32 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCustomerSurvey.cs
> +        public int SecParam { get; set; }
This should be `Unknown1`

2022-05-07 04:32 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCustomerSurvey.cs
> +        Level           = 0x07, // Level as second parameter
What does this comment mean?

2022-05-08 20:59 UTC, ChargeIn commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCustomerSurvey.cs
> +        public int SecParam { get; set; }
The second parameter is not an unknown here, but simply the second parameter of the request. The parameter is defined by the type of the request.

E.g. if you send the client a level survey dialog, the second parameter is the level ( which will be also include in the response).

2022-05-08 21:01 UTC, ChargeIn commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCustomerSurvey.cs
> +        Level           = 0x07, // Level as second parameter
Depending on the type of the survey the request has a second parameter. In case of the level dialog, the second parameter is the level which will be display in the dialog.

2022-05-09 00:51 UTC, kirmmin requested changes

2022-05-09 00:51 UTC, kirmmin commented on Source/NexusForever.Shared/Network/Message/GameMessageOpcode.cs
> +        ServerNewCustomerSurvey         = 0x033E,
You have Client and Server mixed up on this. This prefix is used to denote the sender of the packet. In this case, Client is sending a survey in and Server is sending a survey received response.

2022-05-09 00:51 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientCustomerSurvey.cs
> +        public short Answer1 { get; private set; }
Rather than Answer1 - Answer4, you would be better having Classes that denote the field names appropriately, then have the Reader read as a Class based on the `SurveyType`.

2022-05-09 00:51 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Handler/MiscHandler.cs
> +        {
What's the plan with this? Do you intend to store them in the database to be read by a UI?

2022-05-09 18:09 UTC, ChargeIn commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientCustomerSurvey.cs
> +        public short Answer1 { get; private set; }
While you are totally right with this, I would suggest keeping it this way for now. The original surveys will probably not been used in the way they were intendet. 

The idea was to keep the survey implementation so future content creators can use them to get feedback for new content.  Implementing all type now is probably a waste of time since most of them will never been used.

But if you still want them I can implement them. (for the sake of completeness)

2022-05-09 18:11 UTC, ChargeIn commented on Source/NexusForever.WorldServer/Network/Message/Handler/MiscHandler.cs
> +        {
Yes, that is the idea behind it, but implementing it now does not make sense. The idea was to keep so people can get feedback once they implement new content.

2022-05-09 22:27 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientCustomerSurvey.cs
> +        public short Answer1 { get; private set; }
I think we would prefer for those who wish to modify the client to also modify the server to their needs. If they're adding/removing SurveyType's, they can go so far as to add/remove a Class that supports it for the purpose of the database.

2022-05-16 21:17 UTC, ChargeIn commented on Source/NexusForever.Shared/Network/Message/GameMessageOpcode.cs
> +        ServerNewCustomerSurvey         = 0x033E,
I guess the naming is bad here, but the prefixes are correct. The ServerNewCustomerSurvey is send by the server to the client to create the survey popup. After the user filled out the survey the client sends the ClientCustomerSurveyResponse to the server. 

Should I adjust the naming?

2022-05-16 21:20 UTC, kirmmin commented on Source/NexusForever.Shared/Network/Message/GameMessageOpcode.cs
> +        ServerNewCustomerSurvey         = 0x033E,
Yeah, I would reverse them:
- ServerCustomerSurveyResponse
- ClientCustomerSurveyCreate

2022-05-16 21:22 UTC, kirmmin commented on Source/NexusForever.Shared/Network/Message/GameMessageOpcode.cs
> +        ServerNewCustomerSurvey         = 0x033E,
`ClientCustomerSurveySubmit` is probably better than Create, so I'd go with that :P

2022-06-21 10:50 UTC, Rawaho commented on Source/NexusForever.Shared/Network/Message/GameMessageOpcode.cs
> +        ServerCustomerSurveyResponse    = 0x033E,
When the client receives this packet it invokes a LUA function called NewCustomerSurveyRequest, could potentially name the packet around this.

2022-06-21 10:50 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCustomerSurvey.cs
> +        public int SecParam { get; set; }
From what I can see this second parameter is the index/id, seems it is used to queue multiple surveys.
If you send this packet twice with values 0 and 1 it will show the second survey after the first is completed or ignored.
By default it seems the client supported 3? This is just what I have noticed from the quick look at the CustomerSurvey LUA code.

2022-06-21 10:50 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCustomerSurvey.cs
> +    public enum SurveyType
Might want to move this to a separate file.
Usually we try to stick to a single definition (class, enum, etc...) per file unless it is nested.
In this case SurveyType is used by multiple different classes so probably should go into the static folder.

2022-06-21 10:50 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientCustomerSurvey.cs
> +    public class QuestDifficultySurvey : Survey
Same as below, might want to nest these classes.

2022-06-21 10:50 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientCustomerSurvey.cs
> +    public abstract class Survey {
Does this need to be an abstract class, would an interface do the job?
```csharp
interface ISurvey : IReadable
{
   // bla
}
```

2022-07-10 11:52 UTC, ChargeIn commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientCustomerSurvey.cs
> +    public class QuestDifficultySurvey : Survey
Moved it to an own file and wrapped it with a Survey class. But since we cannot extract anything common among these classes, nesting does not bring any advantage.

2022-07-10 12:02 UTC, ChargeIn commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerCustomerSurvey.cs
> +        public int SecParam { get; set; }
As stated above the second parameter is used in some dialogs to add addition information, e.g. if you send a level survey and set the second parameter to 10 it will show ".... Level 10" in the title of the Survey. So if suggestion with the id is true than there need to be a thrid parameter.

2023-07-25 07:44 UTC, merged