Vendor implementation
NexusForever/NexusForever pull request #56
Opened 2018-12-06 18:34 UTC by Matt-Hurd

* Selling to vendor
* Buying from vendor
* Buyback

Important TODOs:
* Figure out item cost calculation from GameFormula

2018-12-12 16:34 UTC, Rawaho requested changes
Just a few issues that need addressing.

2018-12-12 16:34 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientVendorSell.cs
> +            Quantity = (uint)reader.ReadInt();
There a reason you can't just call ReadUInt here?

2018-12-12 16:34 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerBuybackItemsUpdated.cs
> +        public uint UnkE { get; set; } = 0;
There is no need to specify integer defaults of 0

2018-12-12 16:34 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Handler/VendorHandler.cs
> +            session.Player.Inventory.ItemCreate(itemEntry.Id, vendorPurchase.VendorItemQty * itemEntry.BuyFromVendorStackCount);
Be aware that this won't work in all cases.
Items that has specific attributes assigned to them will be lost on repurchase.

2018-12-12 16:34 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Handler/VendorHandler.cs
> +            ulong calculatedCost1 = (ulong)(itemEntry.CurrencyAmount1 * costMultiplier);
I would suggest using the GameTableFieldArrayAttribute here to remove the need to check both currencies explicitly

2018-12-12 16:34 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +        public uint highestBuybackId = 0; // TODO Clean this implementation
Maybe just iterate BuybackItems and find the highest BuybackItemId and +1?

2018-12-15 06:13 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +        public uint highestBuybackId = 0; // TODO Clean this implementation
The game expects a unique buybackId to be sent. ie:
BuybackItems 1-5 are available, you buy 5, the next one should still be 6.

2019-01-06 11:13 UTC, Rawaho approved these changes

2019-01-07 12:41 UTC, merged