Path - Update Enum & Packet Classes
NexusForever/NexusForever pull request #61
Opened 2018-12-07 05:26 UTC by kirmmin

Updated Player.cs to expose ServerPathLog properties

2018-12-08 04:14 UTC, kirmmin commented
The following commit contains further updates to this: https://github.com/lucas-jones/NexusForever/commit/93833e0149c7de14b177ec8c8fe19b599262fe9f

2018-12-12 17:11 UTC, Rawaho requested changes

2018-12-12 17:11 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPathLog.cs
> +        **/
This doesn't need to be a comment.
Either create an enum for this or use the existing path enum and just bitshift it 1 << path which will result in the same thing.

2018-12-12 17:11 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Static/Path.cs
> +        Explorer = 3,
To follow with the rest of the project style, you only need to explicitly give the values when the enum isn't sequential or doesn't start from 0

2018-12-12 17:11 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +
Extra space doesn't need to be there

2018-12-18 16:49 UTC, kirmmin commented
This is complete and ready for merge. This sets us up to bring in the work currently happening over on https://github.com/kirmmin/NexusForever/tree/player-path-management. This branch, as of this posting, enables path data upon character creation & defaults to soldier if no path data available upon logging in.
There will be some updates to path switching and /who results in relation to this, too.

Big thanks to @lucas-jones for all the help with path opcodes as we build out this piece.

2018-12-23 04:30 UTC, kirmmin commented
Replaced by #74

2018-12-23 04:30 UTC, closed without merging