Player packet identification
NexusForever/NexusForever pull request #62
Opened 2018-12-07 16:02 UTC by kirmmin

2018-12-09 06:58 UTC, Rawaho requested changes

2018-12-09 06:58 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Network/Model/PlayerEntityModel.cs
> +        public byte PvPEnabled { get; set; } // 0 = off, 1+ = on
Having an enum and calling this `PvpFlags` would be better as it has more than 2 values.
From the quick look I had in the client I had, 0x01 is called flagged, and 0x02 is called forced

2018-12-09 20:26 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Network/Model/PlayerEntityModel.cs
> +        public byte PvPEnabled { get; set; } // 0 = off, 1+ = on
Gotcha :) I'll get working on that. I have some sniffs from another member, and one of them had 6 as the value in this field. Any chance you could tell me what 6 might mean?

2018-12-09 21:09 UTC, kirmmin commented
```
{ id: 453416705,
  realmId: 388,
  name: '<Name Redacted>',
  race: 'Mordesh',
  clazz: 'Stalker',
  sex: 'Male',
  Unknown20: 0,
  Unknown2C_Length: 0,
  Unknown2C: '',
  guildName: '<Guild Name Redacted>',
  unknown34: 5,
  Unknown3C_Length: 2,
  Unknown3C: '0xFF91 0xFEBA ',
  Bones_Length: 14,
  Bones: '0x0001 0x0000 0x0000 0x0000 0x0001 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 0x0000 ',
  PvP: 0,
  Unknown4C: 0,
  TitleId: 0 }
```
This is part of the sniff that was sent to me by @lucas-jones on Discord, who confirmed the `realmId` placement, possibly used for cross-server battles amongst other things.

2018-12-11 09:00 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +                RealmId  = 358,
358 seems like a magic number here, can we extract it as a const?

2018-12-11 17:14 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +                RealmId  = 358,
As I understand it, it was the EU server Realm ID. I think we'd want to update this to be the realm that the user is actually connecting on.
I can dig through the code and see if it's exposed. I should think we can get a reference to it, or create one, either way.

2018-12-11 17:15 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +                RealmId  = 358,
This functionality already exists on the housing branch (housing does some weird stuff if the realm id doesn't match), no need to add an implementation for it

2018-12-11 17:16 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Network/Model/PlayerEntityModel.cs
> +        public byte PvPEnabled { get; set; } // 0 = off, 1+ = on
This should be ready for your resolution & sign off, @Rawaho. Thanks.

2018-12-11 17:19 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +                RealmId  = 358,
Good to know. Thanks @Rawaho. Is this part of the PR fine to leave, then, as it'll get replaced by the housing branch? Alternatively, do you need me to remove the `RealmId` reference?

2018-12-11 17:20 UTC, lucas-jones commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +                RealmId  = 358,
356 is US realm I believe. We should be using a consistent realmId otherwise it causes inconsistencies and the client been confused.

If Rawaho has a solution for this in the housing branch we can easily sort this :)

2018-12-12 17:17 UTC, Rawaho requested changes

2018-12-12 17:17 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Static/PvPFlag.cs
> +        Unknown     = 6 // Same deal as PvPFlag.Forced.
This doesn't need to be a member, it's just a combination of 2 flags, 2 | 4, also needs the Flags attribute

2018-12-12 17:17 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Static/Stat.cs
> +        // Stat(32) Duplicates Health, Stat(33) Duplicates Focus, and so on. Seems to loop at this point, suggesting a maximum of 32 "Stats".
Not sure what you mean here by "Must be float. How do we enforce?"

2018-12-12 18:08 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Static/Stat.cs
> +        // Stat(32) Duplicates Health, Stat(33) Duplicates Focus, and so on. Seems to loop at this point, suggesting a maximum of 32 "Stats".
Some stats fail to work when they are `int` and will only work when sent in as `float`. Not sure how we enforce a 'stat type' e,.g. `int` or `float`, based on the Enum?

2018-12-12 18:08 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Static/PvPFlag.cs
> +        Unknown     = 6 // Same deal as PvPFlag.Forced.
Thank you. I will get this updated (and I'll try out `4` as well :p

2018-12-13 14:46 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Static/PvPFlag.cs
> +        Unknown     = 6 // Same deal as PvPFlag.Forced.
`4` doesn't seem to do anything different. Are we assuming that there is a 4 but we don't know what it is yet, given that we have logs that show a `6`?

2018-12-13 14:55 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Static/PvPFlag.cs
> +        Unknown     = 6 // Same deal as PvPFlag.Forced.
I removed it for now - we can add it back in, should that be necessary. The 4 states that I can see for PvP are available with the first 3 flags.

2018-12-24 09:53 UTC, merged