Player faction updates
NexusForever/NexusForever pull request #63
Opened 2018-12-07 19:55 UTC by kirmmin

Sets faction at creation
Applies factionId to character table

2018-12-07 19:58 UTC, kirmmin commented
I have questions around `ServerPlayerCreate.Faction` & `Faction1` in Entitiy Model.

`ServerPlayerCreate.Faction`: This seems to be tied to some other value, as it did not affect my character's "display" of faction or reputation values.
`EntityModel.Faction1` - Not sure what this is used for as Faction2 is clearly in relation to the player's actual faction value. Could be an NPC or 'faction usable' flag? It was also mentioned by neone, on Discord, that it could be in relation to regional factions.

2018-12-10 14:54 UTC, jasoncouture commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPlayerCreate.cs
> +            public List<FactionReputation> FactionReputations { get; set; } = new List<FactionReputation>();
This should probably be get only, use .Add .Clear, and .AddRange to modify it.

2018-12-10 16:37 UTC, kirmmin commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPlayerCreate.cs
> +            public List<FactionReputation> FactionReputations { get; set; } = new List<FactionReputation>();
Yea, this was me testing. I hard-set it and it wasn't working in the client, so I stopped updates of it until I've had chance to revisit it and understand that piece. I can remove that line of commit, too.

2018-12-11 17:11 UTC, kirmmin commented
This should be finalised and ready for merge. This PR focuses solely on setting up the character to be on the right faction, and extend that logic into the right classes.
I have started work on a reputation manager which will take on the rest of the faction piece for `Players`: https://github.com/kirmmin/NexusForever/tree/reputation-management

2018-12-12 17:19 UTC, Rawaho requested changes

2018-12-12 17:19 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +            Faction2    = model.FactionId;
What about existing characters? Will this crash the client since it will be set to 0?

2018-12-12 17:19 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +                    FactionId = 166, // This does not do anything for the player's "main" faction. Exiles/Dominion
Afaik this sets your faction in the character window, should be the same as the one in the database

2018-12-12 18:09 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +            Faction2    = model.FactionId;
It didn't, for me. It seemed to re-default to Dominion.

2018-12-12 18:11 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +                    FactionId = 166, // This does not do anything for the player's "main" faction. Exiles/Dominion
I thought the same thing, but didn't seem to do anything, which led me to figuring out `Faction2`'s use. I'm wondering if it's been misidentified, or was for something else. Trying other values in it, like `167`, `0` or `1` did nothing in my testing.

2018-12-13 14:40 UTC, Rawaho approved these changes

2018-12-13 14:42 UTC, merged