Title implementation
NexusForever/NexusForever pull request #64
Opened 2018-12-08 21:47 UTC by IceReaper

Well.. Titles fully implemented. Do i need to say more? :D

2018-12-10 15:05 UTC, jasoncouture approved these changes
Looks good to me.

2018-12-11 08:56 UTC, Matt-Hurd reviewed
Some minor nitpicks, feel free to reject them if you disagree.

2018-12-11 08:56 UTC, Matt-Hurd commented on Source/NexusForever.Shared/Network/Message/GameMessageOpcode.cs
> +        ClientChat                      = 0x01C3,
Nitpick, but reordering things like this should be in it's own PR in order to minimize the risk of needing to rebase and merge in changes. At the very least, having them in their own commit is a good start.

2018-12-11 08:56 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Command/Handler/TitleCommandHandler.cs
> +                return Task.CompletedTask;
I'm not too familiar with C# threading, but is there a different status that should be sent? CompletedTask has a status of `RanToCompletion` which means `The task completed execution successfully.`. That doesn't seem perfect. At the very least, there should be some logging or response here to tell the client that the command had the incorrect number of parameters.

2018-12-11 08:56 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Command/Handler/TitleCommandHandler.cs
> +                return Task.CompletedTask;
See above comment.

2018-12-11 08:56 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Game/Entity/TitleManager.cs
> +        public void Remove(ulong title)
Is there actually any mechanic that removes titles, outside of dev commands? This adds some extra complexity that hurts readability.

2018-12-11 08:56 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Network/Message/Model/Server0169.cs
> -﻿using NexusForever.Shared.Network;
Changes like this shouldn't be included in the PR. Selectively adding files, and using `git add -p` can help avoid commiting extra files.

2018-12-11 08:56 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerTitlesUpdate.cs
> +                writer.Write(0, 16); // TODO
Some context on this TODO would be 👍

2018-12-12 18:23 UTC, Rawaho requested changes
Great work, just a few smaller things that need addressing

2018-12-12 18:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerTitleAdd.cs
> +        public ulong Title { get; set; }
This should be ushort, no need for it to be such a large data type

2018-12-12 18:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerTitleSet.cs
> +        public ulong Title { get; set; }
Same as above

2018-12-12 18:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerTitlesUpdate.cs
> +            foreach (var title in Titles)
This needs to be encapsulated in it's own class with the IWritable attribute

2018-12-12 18:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientTitleSet.cs
> +            TitleId = reader.ReadUShort();
This should be 14 bits

2018-12-12 18:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/TitleManager.cs
> +        public void Update()
This should be renamed to something like SendTitlesUpdate to avoid confusion with the common Update function used in a lot of classes to handle world tick

2018-12-12 18:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/TitleManager.cs
> +    }
Try keep single class, structure, enum, interface, ect... per source file unless nested
Enums generally want to go into the Static folder

2018-12-12 18:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/TitleManager.cs
> +                if ((value != 0 && (!owned.ContainsKey(value) || owned[value] == SaveStatus.Deleted)) || active == value)
This is too many checks for a single statement, either create multiple or split them grouped by line

2018-12-12 18:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/TitleManager.cs
> +            set
Is there actually a case where you'll be mass setting titles?

2018-12-12 18:23 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/TitleManager.cs
> +        private ulong active;
This can be a ushort

2018-12-12 20:12 UTC, jasoncouture commented on Source/NexusForever.WorldServer/Command/Handler/TitleCommandHandler.cs
> +                return Task.CompletedTask;
Regarding C# tasks, this is correct. However, it shouldn't be necessary here, because it should be async Task
with `
{
    await SendHelpAsync(context);
    return;
}
`

instead of
`return Task.CompletedTask;`

The reason for using Task.CompletedTask is for non-async code in a sync context (async/await is not necessarily threading). This allows avoiding compiler warnings about async methods that run synchronously.

2018-12-12 20:13 UTC, jasoncouture requested changes
See comments added after @Matt-Hurd about SendHelpAsync();

2018-12-12 20:14 UTC, jasoncouture commented on Source/NexusForever.WorldServer/Command/Handler/TitleCommandHandler.cs
> +                return Task.CompletedTask;
You could also `return SendHelpAsync(context);` which is arguably more correct.

2018-12-12 20:15 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerTitleAdd.cs
> +        public ulong Title { get; set; }
My mistake

2018-12-12 20:16 UTC, MaxtorCoder commented on Source/NexusForever.WorldServer/Game/Entity/TitleManager.cs
> +            set
There would be when being a GM or testing stuff?

2018-12-12 20:38 UTC, IceReaper commented on Source/NexusForever.WorldServer/Game/Entity/TitleManager.cs
> +    }
I thought this enum might be usefull in general for other classes so i added the todo. Ill move it.

2018-12-31 01:16 UTC, kirmmin commented
I'm looking to get this PR finalised and merged in so that I can add Title Updates to #74 on Level Up. @IceReaper, do you plan to update after @Rawaho's feedack, or would you like someone else to finish off the branch?

2019-01-02 12:44 UTC, Rawaho approved these changes

2019-01-02 12:53 UTC, merged

2019-01-04 22:49 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/TitleManager.cs
> +                var model = new Character
Creating a new Character model is breaking saving an existing one, in my experience. For example, I was modifying my path XP on my branch, and after changing my title, I could no longer make changes to the path XP and my location stopped saving.
@Rawaho , did you experience this at all?