Persistent Character location
NexusForever/NexusForever pull request #65
Opened 2018-12-09 01:31 UTC by ahoiahoi

Store player location in the DB

2018-12-09 06:42 UTC, Rawaho commented
Location and world is already stored on every grid entity, there is no need to have them duplicated on the player too.
My suggestion would be using `OnRelocate` override to set the save mask for location and when the actual save occurs pull the location from the grid entity.

2018-12-09 20:20 UTC, ahoiahoi commented
@Rawaho good idea, thank you

2018-12-12 18:30 UTC, Rawaho requested changes
Just a single small change

2018-12-12 18:30 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +            Map.Entry.Id = (ushort)map.Entry.Id;
Both position and map are set before this in `base.OnAddToMap`, no need to do it again

2018-12-12 20:09 UTC, ahoiahoi commented
@Rawaho updated

2018-12-13 14:31 UTC, Rawaho approved these changes

2018-12-13 14:32 UTC, merged