Player Path Management
NexusForever/NexusForever pull request #74
Opened 2018-12-23 04:29 UTC by kirmmin

Closes #61 

Related to #24 

**Features**
- Unlocking Paths
- Activation of Paths
- Character Database table for storing of data
- Unlocking & Activation of Paths works from the Path Log, but will need Service Tokens to make it happen. (PR Link shortly for that)
- Commands are also available to unlock & activate paths for the current character.
- Adds in many other path-related opcodes to be used by missions and other things as the features are developed
- Fixes the display of path on the character window
- Fixes the display of player's paths on tooltip hover
- Handles tracking and rewarding of experience for all player paths
- Handles rewarding the correct reward(s) on level up (NB: Missing spell rewards currently)

**Commands**
- `!path unlock <pathId`
    - Unlocks a path if the player hasn't unlocked it already.
- `!path activate <pathId>`
    - Activates a path if the player has it unlocked.
- `!path addxp <value>`
    - Adds the <value> of experience to the current active path.

**Path IDs**
- Soldier: `0`
- Settler: `1`
- Scientist: `2`
- Explorer: `3`

2018-12-23 07:29 UTC, Rawaho requested changes
Great work, mostly just small issues and nitpick stuff

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ClientPathUnlock.cs
> +            Path = (Path)reader.ReadByte(3);
A cleaner way of reading this would be `reader.ReadEnum<Path>(3)`

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPathLog.cs
> +        public Progress PathProgress { get; set; }
Packet models should match the models found in the client, the client does not have a structure here, it's just a uint array

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/ServerPathMissionActivate.cs
> +            public uint Unknown5 { get; set; }
Client calls values in the Mission struct the following:
```
MissionId
Completed
Userdata
Statedata
Reason
Giver
```

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Network/Message/Model/Server06B9.cs
> +            writer.Write(Unknown2, Unknown1 * 4);
Unknown1 will be a counter for an array with values of 4 bytes (uint, float, ect) in length.

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Player.cs
> +            }
Code blocks of only one line shouldn't have braces, this happens in a few places

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/PathManager.cs
> +            return pathUnlocked;
This function isn't needed, you can calculate the mask `(PathUnlocked)(1 << path)`

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/PathEntry.cs
> +        public PathUnlocked PathsUnlocked {
Needs to be Allman style, same below too

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/PathEntry.cs
> +                if(soldierXp < 0 || value != soldierXp)
No need to check for negative numbers, variable type is unsigned

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/PathEntry.cs
> +        public PathEntry()
There should never be a point where you need to create an empty PathEntry

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/PathManager.cs
> +        public PathManager() { }
There should never be a point where you need to create an empty PathManager

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/PathManager.cs
> +            if (pathEntry.ActivePath == pathToCheck)
Might be better to replace this with just `return pathEntry.ActivePath == pathToCheck;`

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/PathManager.cs
> +            if (IsPathUnlocked(pathToActivate))
Try and reduce nested code, something like
```
if (!IsPathUnlocked(pathToActivate))
     throw new ArgumentException("Path is not unlocked.");
```

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/PathManager.cs
> +            if(player == null)
Space between if and following bracket, this happens in a few places

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/PathManager.cs
> +            if (player == null)
Do we really need to check for null?
A PathManager should always have an owner

2018-12-23 07:29 UTC, Rawaho commented on Source/NexusForever.WorldServer/Game/Entity/Static/PathUnlocked.cs
> +    public enum PathUnlocked
PathMask is probably a better name, not essential just a thought

2018-12-23 21:22 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Static/PathUnlocked.cs
> +    public enum PathUnlocked
I'd like to keep it as PathUnlocked, for now, until refactoring comes around. My issue with renaming it right now is that I don't know what other masks might be needed for path-related features (rewards given, etc.)

2018-12-23 21:45 UTC, kirmmin commented
All noted review items should be resolved.

2018-12-24 01:29 UTC, Matt-Hurd commented on Source/NexusForever.WorldServer/Game/Entity/Static/PathUnlocked.cs
> +    public enum PathUnlocked
Having it end with `Mask` would still be best to keep naming consistent.

2018-12-24 04:10 UTC, kirmmin commented on Source/NexusForever.WorldServer/Game/Entity/Static/PathUnlocked.cs
> +    public enum PathUnlocked
Renamed to `PathUnlockedMask`

2018-12-31 02:17 UTC, kirmmin commented
Note: Path XP on the XP bar only updates when the player has more than 0 regular XP. It's a code block in the XP Bar's LUA code. When I set my XP to 1 or higher, on load, the Path XP bar would update accordingly.

2019-01-03 19:49 UTC, kirmmin commented
After thinking on this, and adding some more features, I'm seeing a cleaner way to implement this. There's nothing waiting on my work on this currently, so I'm going to spend the next few days refactoring.

@Rawaho would you like me to close this an open a new one after complete, or just merge changes into this PR?

2019-01-06 10:03 UTC, Rawaho approved these changes

2019-01-06 10:03 UTC, merged